// export const people = [
//   { name: 'Adam', id: 1 },
//   { name: 'Ewa', id: 2 },
//   { name: 'Michał', id: 3 },
//   { name: 'Anna', id: 4 },
//   { name: 'Krzysztof', id: 5 },
//   { name: 'Marta', id: 6 },
//   { name: 'Piotr', id: 7 },
//   { name: 'Magdalena', id: 8 },
//   { name: 'Jan', id: 9 },
//   { name: 'Alicja', id: 10 },
//   { name: 'Marek', id: 11 },
//   { name: 'Katarzyna', id: 12 },
//   { name: 'Tomasz', id: 13 },
//   { name: 'Monika', id: 14 },
//   { name: 'Łukasz', id: 15 },
//   { name: 'Beata', id: 16 },
//   { name: 'Andrzej', id: 17 },
//   { name: 'Natalia', id: 18 },
//   { name: 'Wojciech', id: 19 },
//   { name: 'Joanna', id: 20 },
// ];
